$ErrorActionPreference = 'Stop'

$repo = Split-Path -Parent $PSScriptRoot
$source = Join-Path $repo 'Source'

$fxc = Get-Command fxc.exe -ErrorAction SilentlyContinue
if (-not $fxc) {
    $kits = @(
        (Join-Path ${env:ProgramFiles(x86)} 'Windows Kits\10\bin'),
        (Join-Path ${env:ProgramFiles(x86)} 'Windows Kits\8.1\bin')
    ) | Where-Object { Test-Path $_ }
    foreach ($kit in $kits) {
        $candidate = Get-ChildItem -LiteralPath $kit -Filter fxc.exe -File -Recurse -ErrorAction SilentlyContinue |
            Sort-Object FullName -Descending |
            Select-Object -First 1
        if ($candidate) { $fxc = $candidate; break }
    }
}
if (-not $fxc) { throw 'fxc.exe was not found; cannot regenerate SVP baseline shader bytecode.' }
$fxcPath = if ($fxc.Source) { $fxc.Source } else { $fxc.FullName }

$shaders = @(
    @{ Source='NvidiaOpticalFlowSvpClassify.hlsl'; Header='NvidiaOpticalFlowSvpClassifyBytecode.h'; Symbol='g_NvofSvpClassifyBytecode' },
    @{ Source='NvidiaOpticalFlowSvpControl.hlsl'; Header='NvidiaOpticalFlowSvpControlBytecode.h'; Symbol='g_NvofSvpControlBytecode' },
    @{ Source='NvidiaOpticalFlowSvpCoverageScatter.hlsl'; Header='NvidiaOpticalFlowSvpCoverageScatterBytecode.h'; Symbol='g_NvofSvpCoverageScatterBytecode' },
    @{ Source='NvidiaOpticalFlowSvpCoverageFinish.hlsl'; Header='NvidiaOpticalFlowSvpCoverageFinishBytecode.h'; Symbol='g_NvofSvpCoverageFinishBytecode' },
    @{ Source='NvidiaOpticalFlowSvpWarp.hlsl'; Header='NvidiaOpticalFlowSvpWarpBytecode.h'; Symbol='g_NvofSvpWarpBytecode' }
)

foreach ($shader in $shaders) {
    $inputPath = Join-Path $source $shader.Source
    $outputPath = Join-Path $source $shader.Header
    Write-Host "Compiling $($shader.Source) -> $($shader.Header)"
    # FXC warns (X3556) on deliberate integer divisions used to preserve SVP's
    # truncation semantics.  Do not promote that performance warning to an
    # error; shader compile errors still return a non-zero exit code below.
    & $fxcPath /nologo /T cs_5_0 /E main /O3 /Fh $outputPath /Vn $shader.Symbol $inputPath
    if ($LASTEXITCODE -ne 0) { throw "fxc failed for $($shader.Source) with exit code $LASTEXITCODE" }

    # FXC pads much of its generated listing/header text with trailing spaces.
    # Normalize that deterministic output so generated bytecode headers pass
    # the repository's whitespace checks and produce reviewable diffs.
    $normalized = [System.IO.File]::ReadAllLines($outputPath) | ForEach-Object { $_.TrimEnd() }
    [System.IO.File]::WriteAllText(
        $outputPath,
        (($normalized -join "`n") + "`n"),
        [System.Text.UTF8Encoding]::new($false))
}

Write-Host 'Regenerated SVP-style native NVOF baseline shader bytecode.'
